# Generated by Django 3.1.6 on 2021-05-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('producent', models.CharField(max_length=30, verbose_name='Producent')),
                ('description', models.CharField(max_length=150, verbose_name='Descirption')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('deleted', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='movies', to='movie.Category')),
            ],
        ),
    ]
