# Generated by Django 3.1.6 on 2021-05-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='itw_category',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='itw_movie',
        ),
    ]
