# Generated by Django 3.1.6 on 2021-05-03 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210502_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Descirption')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('season_no', models.IntegerField(verbose_name='Number of seasons')),
                ('deleted', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='categories', to='movie.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Descirption')),
                ('episode_no', models.IntegerField(verbose_name='Number of epiosdes')),
                ('deleted', models.BooleanField(default=False)),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movie.serial')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Descirption')),
                ('deleted', models.BooleanField(default=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movie.season')),
            ],
        ),
    ]
