# Generated by Django 3.1.6 on 2021-02-02 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210202_1917'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0002_auto_20210202_1917'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'OrderUnit',
                'verbose_name_plural': 'OrderUnites',
                'db_table': 'itw_order_units',
            },
        ),
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name': 'Counter', 'verbose_name_plural': 'Counters'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_registerd',
            new_name='date_registered',
        ),
        migrations.AddField(
            model_name='order',
            name='creator_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='agent.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counter',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='code_year',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='counter',
            table='itw_counter',
        ),
        migrations.AlterModelTable(
            name='order',
            table='itw_order',
        ),
        migrations.DeleteModel(
            name='Order_Unit',
        ),
        migrations.AddField(
            model_name='orderunit',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='orderunit',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
