# Generated by Django 3.1.6 on 2021-04-04 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210202_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderunit',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_units', to='order.order'),
        ),
    ]
